config/routes.rb
Rails4landing::Application.routes.draw do
  resources :subscribers

  devise_for :users, controllers: { registrations: "users/registrations" }

  root 'static#index'
  get '/about', to: 'static#about', as: "about"
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  #
  # Validations
  #
  validates_presence_of :email
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable # :registerable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
  before_filter :set_meta_data

  def set_meta_data(title="App Title", keywords="your, app, keywords", description="A description of your app.")
    @meta_title, @meta_keywords, @meta_description = title, keywords, description
  end

  # Higly recommend using Mixpanel.com to track conversion on landing page
  # Just sign up and insert API tokens below
  # def mixpanel
  #   if Rails.env.production?
  #     # Production Mixpannel Application
  #     @mixpanel ||= Mixpanel::Tracker.new "YourProductionTokenHere", { :env => request.env }
  #   else
  #     # Development Mixpannel Application
  #     @mixpanel ||= Mixpanel::Tracker.new "YourDevelopmentTokenHere", { :env => request.env }
  #   end
  # end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index]
  def index
    @subscriber = Subscriber.new
    # mixpanel.track "Landing page viewed" - Uncomment after mixpanel setup in application_controller.rb
  end

  def about

  end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, only: [:new, :create]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        # mixpanel.set @subscriber.email - Uncomment after mixpanel setup in application_controller.rb
        # mixpanel.track "Subscribed" - Uncomment after mixpanel setup in application_controller.rb
        # SubscriberMailer.new_subscription(@subscriber).deliver - Uncomment after email setup in config/environment/production.rb
        format.html { redirect_to root_url, notice: 'Thank you! Your interest is appreciated.' }
        format.json { render action: 'show', status: :created, location: @subscriber }
      else
        format.html { render action: 'new' }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/3rd_party/_google.html.erb
<% if Rails.env.production? %>
<!--  Insert google analytics script here -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @meta_title %></title>
	<meta name="keywords" content="<%= @meta_keywords %>" />
	<meta name="description" content="<%= @meta_description %>" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render "3rd_party/google" %>
</head>
<body class="application <%= controller.controller_name %> <%= controller.controller_name %>-<%= controller.action_name %>">
  <%= render "shared/notice" %>
  <%= render "shared/navbar" %>
  <div class="yield">
    <%= yield %>
  </div>
  <%= render "shared/footer" %>
</body>
</html>

app/views/shared/_footer.html.haml
.container.mtxl.mbxl
  .row
    .col-md-3

    .col-md-6
      %span.text-muted Built by
      = link_to "YourCompany", "#"

    .col-md-3

app/views/shared/_navbar.html.haml
.container
  .row
    .col-md-6.ptm
      = render "shared/twitter_btn"
    .col-md-6.text-right.ptm

      - if current_user
        %span.text-muted
          Logged in as
          %b= current_user.email
          |
        = link_to "Logout", destroy_user_session_path(@resource), method: :delete if current_user
      - else
        %span.text-muted Already invited?
        = link_to "Sign in", new_user_session_path unless current_user

app/views/shared/_notice.html.haml
- if flash[:error] and !flash[:error].blank?
  .alert.alert-error.fade.in
    %a.close{"data-dismiss" => "alert", href: "#"} ×
    .container
      %p.error= flash[:error]
- if flash[:notice] and !flash[:notice].blank?
  .alert.alert-info.fade.in
    %a.close{"data-dismiss" => "alert", href: "#"} ×
    .container
      %p.notice= flash[:notice]
- if flash[:alert] and !flash[:alert].blank?
  .alert.alert-warning.fade.in
    %a.close{"data-dismiss" => "alert", href: "#"} ×
    .container
      %p.notice= flash[:alert]

app/views/shared/_twitter_btn.html.erb
<a href="https://twitter.com/YourApp" class="twitter-follow-button" data-show-count="false">Follow @YourApp</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/subscribers/_form.html.haml
= form_for @subscriber do |f|
  - if @subscriber.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subscriber.errors.count, "error")} prohibited this subscriber from being saved:"
      %ul
        - @subscriber.errors.full_messages.each do |msg|
          %li= msg

  .row
    .col-md-7
      .form-group
        = f.text_field :email, placeholder: "Enter email address"
    .col-md-5
      = f.submit 'Reserve Your Spot', :class => "btn btn-danger btn-lg"
      %p.text-muted.pam
        Beta invites to be sent out soon.

app/views/subscribers/index.html.haml
%h1 Listing subscribers

%table
  %tr
    %th Email
    %th
    %th
    %th

  - @subscribers.each do |subscriber|
    %tr
      %td= subscriber.email
      %td= link_to 'Show', subscriber
      %td= link_to 'Edit', edit_subscriber_path(subscriber)
      %td= link_to 'Destroy', subscriber, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Subscriber', new_subscriber_path

app/views/subscribers/new.html.haml
%h1 New subscriber

= render 'form'

= link_to 'Back', subscribers_path

app/views/subscribers/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @subscriber.email

= link_to 'Edit', edit_subscriber_path(@subscriber)
\|
= link_to 'Back', subscribers_path